name: tranyx_web
description: A new Jaspr project
version: 0.0.1
resolution: workspace
environment:
  sdk: ^3.11.5

dependencies:
  crypto: ^3.0.6
  http: ^1.6.0
  jaspr: ^0.23.1
  jaspr_router: ^0.9.0
  meta: ^1.16.0
  shared: any
  web: ^1.1.1

dev_dependencies:
  build_daemon: ^4.1.4
  build_runner: ^2.15.0
  build_web_compilers: ^4.5.1
  dart_style: ^3.1.7
  jaspr_builder: ^0.23.1
  lints: ^6.0.0
  test: ^1.25.8

jaspr:
  mode: client
  # Pass --dart-define=ENV=dev|uat|prod to jaspr serve/build.
  # Example:
  #   dart run jaspr:jaspr serve --dart-define=ENV=dev
  #   dart run jaspr:jaspr build --dart-define=ENV=prod

scripts:
  serve-dev: dart run shared:generate_env && dart run jaspr:jaspr serve --dart-define=ENV=dev
  serve-uat: dart run shared:generate_env && dart run jaspr:jaspr serve --dart-define=ENV=uat
  serve-prod: dart run shared:generate_env && dart run jaspr:jaspr serve --dart-define=ENV=prod
  build-dev: dart run shared:generate_env && dart run jaspr:jaspr build --dart-define=ENV=dev
  build-uat: dart run shared:generate_env && dart run jaspr:jaspr build --dart-define=ENV=uat
  build-prod: dart run shared:generate_env && dart run jaspr:jaspr build --dart-define=ENV=prod