// Job category constants — mirrors React JOB_GROUPS constant.
// Each group has: id, label, icon (lucide name), color (Tailwind text class), and categories list.
import 'models.dart';

const kJobGroups = [
  JobGroup(
    id: 1,
    label: 'Home Repair & Maintenance',
    icon: 'hammer',
    color: 'text-amber-600',
    categories: [
      CategoryItem(id: 101, label: 'Electrician', icon: 'zap'),
      CategoryItem(id: 102, label: 'Plumber', icon: 'droplet'),
      CategoryItem(id: 103, label: 'Painter', icon: 'paintbrush'),
      CategoryItem(id: 104, label: 'Locksmith', icon: 'key'),
      CategoryItem(id: 105, label: 'Carpenter', icon: 'hammer'),
      CategoryItem(id: 106, label: 'Roofer', icon: 'home'),
      CategoryItem(id: 107, label: 'Tiler', icon: 'layout-grid'),
      CategoryItem(id: 108, label: 'Mason', icon: 'building'),
    ],
  ),
  JobGroup(
    id: 2,
    label: 'Cleaning & Organizing',
    icon: 'sparkles',
    color: 'text-indigo-500',
    categories: [
      CategoryItem(id: 201, label: 'House Cleaning', icon: 'sparkles'),
      CategoryItem(id: 202, label: 'Laundry', icon: 'shirt'),
      CategoryItem(id: 203, label: 'Car Wash', icon: 'car'),
      CategoryItem(id: 204, label: 'Office Cleaning', icon: 'building'),
      CategoryItem(id: 205, label: 'Window Cleaning', icon: 'wind'),
    ],
  ),
  JobGroup(
    id: 3,
    label: 'Outdoor & Garden',
    icon: 'flower-2',
    color: 'text-green-600',
    categories: [
      CategoryItem(id: 301, label: 'Gardener', icon: 'flower-2'),
      CategoryItem(id: 302, label: 'Pool Cleaning', icon: 'waves'),
      CategoryItem(id: 303, label: 'Lawn Mowing', icon: 'flower-2'),
      CategoryItem(id: 304, label: 'Tree Trimming', icon: 'flower-2'),
    ],
  ),
  JobGroup(
    id: 4,
    label: 'Automotive',
    icon: 'wrench',
    color: 'text-sky-500',
    categories: [
      CategoryItem(id: 401, label: 'Mobile Mechanic', icon: 'wrench'),
      CategoryItem(id: 402, label: 'Towing', icon: 'truck'),
      CategoryItem(id: 403, label: 'Oil Change', icon: 'droplet'),
      CategoryItem(id: 404, label: 'Tire Fitting', icon: 'wrench'),
    ],
  ),
  JobGroup(
    id: 5,
    label: 'Delivery & Errands',
    icon: 'package',
    color: 'text-orange-500',
    categories: [
      CategoryItem(id: 501, label: 'Grocery Delivery', icon: 'package'),
      CategoryItem(id: 502, label: 'Document Runner', icon: 'file-text'),
      CategoryItem(id: 503, label: 'Courier', icon: 'truck'),
      CategoryItem(id: 504, label: 'Pharmacy Pickup', icon: 'package'),
    ],
  ),
  JobGroup(
    id: 6,
    label: 'Moving & Logistics',
    icon: 'truck',
    color: 'text-blue-600',
    categories: [
      CategoryItem(id: 601, label: 'Furniture Moving', icon: 'truck'),
      CategoryItem(id: 602, label: 'Packing', icon: 'package'),
      CategoryItem(id: 603, label: 'Relocation', icon: 'map-pin'),
      CategoryItem(id: 604, label: 'Storage', icon: 'package'),
    ],
  ),
  JobGroup(
    id: 7,
    label: 'Personal Care & Assistance',
    icon: 'heart',
    color: 'text-pink-500',
    categories: [
      CategoryItem(id: 701, label: 'Baby Sitter', icon: 'heart'),
      CategoryItem(id: 702, label: 'Pet Grooming', icon: 'heart'),
      CategoryItem(id: 703, label: 'Tutor', icon: 'book-open'),
      CategoryItem(id: 704, label: 'Personal Assistant', icon: 'user'),
      CategoryItem(id: 705, label: 'Elder Care', icon: 'heart'),
    ],
  ),
  JobGroup(
    id: 8,
    label: 'Tech & IT Support',
    icon: 'monitor',
    color: 'text-blue-500',
    categories: [
      CategoryItem(id: 801, label: 'Software Dev', icon: 'code'),
      CategoryItem(id: 802, label: 'UI/UX Designer', icon: 'pen-tool'),
      CategoryItem(id: 803, label: 'Blockchain Dev', icon: 'globe'),
      CategoryItem(id: 804, label: 'IT Support', icon: 'monitor'),
      CategoryItem(id: 805, label: 'Network Setup', icon: 'globe'),
      CategoryItem(id: 806, label: 'Web Developer', icon: 'code'),
    ],
  ),
  JobGroup(
    id: 9,
    label: 'Business, Finance & Admin',
    icon: 'trending-up',
    color: 'text-emerald-600',
    categories: [
      CategoryItem(id: 901, label: 'Accountant', icon: 'calculator'),
      CategoryItem(id: 902, label: 'HR Manager', icon: 'users'),
      CategoryItem(id: 903, label: 'Virtual Assistant', icon: 'monitor'),
      CategoryItem(id: 904, label: 'Data Entry', icon: 'file-text'),
    ],
  ),
  JobGroup(
    id: 10,
    label: 'Creative & Media',
    icon: 'palette',
    color: 'text-purple-500',
    categories: [
      CategoryItem(id: 1001, label: 'Graphic Designer', icon: 'palette'),
      CategoryItem(id: 1002, label: 'Video Editor', icon: 'activity'),
      CategoryItem(id: 1003, label: 'Photographer', icon: 'camera'),
      CategoryItem(id: 1004, label: 'Copywriter', icon: 'pen-tool'),
      CategoryItem(id: 1005, label: 'Illustrator', icon: 'pen-tool'),
    ],
  ),
  JobGroup(
    id: 11,
    label: 'Marketing & Sales',
    icon: 'trending-up',
    color: 'text-rose-500',
    categories: [
      CategoryItem(id: 1101, label: 'SEO Specialist', icon: 'trending-up'),
      CategoryItem(id: 1102, label: 'Social Media Manager', icon: 'globe'),
      CategoryItem(id: 1103, label: 'Ad Specialist', icon: 'trending-up'),
    ],
  ),
  JobGroup(
    id: 12,
    label: 'Legal, Engineering & Pro Services',
    icon: 'scale',
    color: 'text-zinc-700',
    categories: [
      CategoryItem(id: 1201, label: 'Lawyer', icon: 'scale'),
      CategoryItem(id: 1202, label: 'Civil Engineer', icon: 'building'),
      CategoryItem(id: 1203, label: 'Architect', icon: 'layout-grid'),
      CategoryItem(id: 1204, label: 'Surveyor', icon: 'map-pin'),
    ],
  ),
  JobGroup(
    id: 13,
    label: 'Education & Training',
    icon: 'graduation-cap',
    color: 'text-amber-500',
    categories: [
      CategoryItem(id: 1301, label: 'Online Tutor', icon: 'book-open'),
      CategoryItem(id: 1302, label: 'Corporate Trainer', icon: 'graduation-cap'),
      CategoryItem(id: 1303, label: 'Music Teacher', icon: 'graduation-cap'),
      CategoryItem(id: 1304, label: 'Language Teacher', icon: 'globe'),
    ],
  ),
  JobGroup(
    id: 14,
    label: 'Health & Wellness',
    icon: 'stethoscope',
    color: 'text-red-500',
    categories: [
      CategoryItem(id: 1401, label: 'Health Coach', icon: 'activity'),
      CategoryItem(id: 1402, label: 'Physical Therapist', icon: 'stethoscope'),
      CategoryItem(id: 1403, label: 'Personal Trainer', icon: 'activity'),
      CategoryItem(id: 1404, label: 'Nutritionist', icon: 'stethoscope'),
    ],
  ),
  JobGroup(
    id: 15,
    label: 'Customer Support',
    icon: 'headset',
    color: 'text-blue-500',
    categories: [
      CategoryItem(id: 1501, label: 'Customer Support Rep', icon: 'headset'),
      CategoryItem(id: 1502, label: 'Community Moderator', icon: 'users'),
      CategoryItem(id: 1503, label: 'Live Chat Agent', icon: 'message-square'),
    ],
  ),
  JobGroup(
    id: 16,
    label: 'Miscellaneous & Events',
    icon: 'package',
    color: 'text-zinc-500',
    categories: [
      CategoryItem(id: 1601, label: 'Event Helper', icon: 'users'),
      CategoryItem(id: 1602, label: 'Survey Taker', icon: 'file-text'),
      CategoryItem(id: 1603, label: 'Food Server', icon: 'utensils'),
      CategoryItem(id: 1604, label: 'Others', icon: 'package'),
    ],
  ),
];
