name: Deploy Jaspr to Firebase Hosting on Merge
on:
  push:
    branches:
      - main
      - uat
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Jaspr Web
        run: |
          flutter pub global activate jaspr_cli
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          export PATH="$PATH:$HOME/.pub-cache/bin"
          cd packages/tranyx_web
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            jaspr build --dart-define=ENV=prod
          elif [[ "${{ github.ref_name }}" == "uat" ]]; then
            jaspr build --dart-define=ENV=uat
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            jaspr build --dart-define=ENV=dev
          fi

      - name: Set Environment Variables
        id: set_env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "sa_secret=${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRANYX_APP }}" >> $GITHUB_OUTPUT
            echo "project_id=tranyx-app" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "uat" ]]; then
            echo "sa_secret=${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRANYX_UAT }}" >> $GITHUB_OUTPUT
            echo "project_id=tranyx-uat" >> $GITHUB_OUTPUT
          else
            echo "sa_secret=${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRANYX_DEV }}" >> $GITHUB_OUTPUT
            echo "project_id=tranyx-dev" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ steps.set_env.outputs.sa_secret }}
          projectId: ${{ steps.set_env.outputs.project_id }}
          channelId: live
          entryPoint: packages/tranyx_web