name: Deploy Jaspr to Firebase Hosting on Merge
on:
  push:
    branches:
      - main
      - uat
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: |
          cd packages/tranyx_web
          dart pub get

      - name: Build Jaspr Web
        run: |
          cd packages/tranyx_web
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            dart run jaspr:jaspr build --dart-define=ENV=prod
          elif [[ "${{ github.base_ref }}" == "uat" ]]; then
            dart run jaspr:jaspr build --dart-define=ENV=uat
          elif [[ "${{ github.base_ref }}" == "develop" ]]; then
            dart run jaspr:jaspr build --dart-define=ENV=dev
          fi

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ github.ref_name == 'main' && secrets.FIREBASE_SERVICE_ACCOUNT_TRANYX_APP || github.ref_name == 'uat' && secrets.FIREBASE_SERVICE_ACCOUNT_TRANYX_UAT || secrets.FIREBASE_SERVICE_ACCOUNT_TRANYX_DEV }}
          projectId: ${{ github.ref_name == 'main' && 'tranyx-app' || github.ref_name == 'uat' && 'tranyx-uat' || 'tranyx-dev' }}
          channelId: live
          entryPoint: packages/tranyx_web
